# @package _global_
defaults:
  - basic_oc_base
  - /prior: delta
  - /sde: bm_pis
  - /model@generative_ctrl: score
  - /loss: reference_sde
  - _self_

# Solver
solver:
  _target_: sde_sampler.solver.oc.PIS
